// Read-only reporting: these aggregates span the tables of several modules by nature, so this
// repository reads them directly (never writes). Static SQL, every value is a parameter.
import { type SQL, sql } from "drizzle-orm";
import { z } from "zod";
import type { DbOrTx } from "../../db/client";

const Count = z.coerce.number().int();

async function rows<T extends z.ZodType>(db: DbOrTx, schema: T, query: SQL): Promise<z.infer<T>[]> {
  const result = await db.execute(query);
  return z.array(schema).parse(Array.from(result));
}

async function one<T extends z.ZodType>(db: DbOrTx, schema: T, query: SQL): Promise<z.infer<T>> {
  const [row] = await rows(db, schema, query);
  if (row === undefined) throw new Error("stats: aggregate returned no row");
  return row;
}

// --- One event ---

export function eventRegistrationCounts(db: DbOrTx, eventId: string) {
  return one(
    db,
    z.object({ confirmed: Count, waitlisted: Count, cancelled: Count }),
    sql`select
          count(*) filter (where status = 'confirmed') as confirmed,
          count(*) filter (where status = 'waitlisted') as waitlisted,
          count(*) filter (where status = 'cancelled') as cancelled
        from registration where event_id = ${eventId}`,
  );
}

export function eventTeamCounts(db: DbOrTx, eventId: string) {
  return one(
    db,
    z.object({ confirmed: Count, waitlisted: Count }),
    sql`select
          count(*) filter (where status = 'confirmed') as confirmed,
          count(*) filter (where status = 'waitlisted') as waitlisted
        from team where event_id = ${eventId}`,
  );
}

export function eventAttendanceCounts(db: DbOrTx, eventId: string) {
  return one(
    db,
    z.object({ participants: Count, staff: Count }),
    sql`select
          count(*) filter (where kind = 'participant') as participants,
          count(*) filter (where kind = 'staff') as staff
        from attendance where event_id = ${eventId}`,
  );
}

export function eventStaffCounts(db: DbOrTx, eventId: string) {
  return one(
    db,
    z.object({ slots: Count, places: Count, validated: Count }),
    sql`select
          (select count(*) from staff_slot where event_id = ${eventId}) as slots,
          (select coalesce(sum(capacity), 0) from staff_slot where event_id = ${eventId}) as places,
          (select count(*) from staff_assignment a join staff_slot s on s.id = a.staff_slot_id
            where s.event_id = ${eventId} and a.status = 'validated') as validated`,
  );
}

/** Open points generated by the event's check-ins, by status (sum of the movements). */
export function eventOpenPoints(db: DbOrTx, eventId: string) {
  return one(
    db,
    z.object({ pending: Count, validated: Count, rejected: Count }),
    sql`select
          coalesce(sum(l.delta) filter (where l.status = 'pending'), 0) as pending,
          coalesce(sum(l.delta) filter (where l.status in ('validated', 'exported')), 0) as validated,
          coalesce(sum(l.delta) filter (where l.status = 'rejected'), 0) as rejected
        from open_points_ledger l join attendance a on a.id = l.attendance_id
        where a.event_id = ${eventId}`,
  );
}

export function eventRegistrationsByDay(db: DbOrTx, eventId: string) {
  return rows(
    db,
    z.object({ day: z.string(), count: Count }),
    sql`select to_char(created_at at time zone 'Europe/Paris', 'YYYY-MM-DD') as day, count(*) as count
        from registration where event_id = ${eventId}
        group by 1 order by 1`,
  );
}

// --- A school year ---

export type YearRange = { startsOn: string; endsOn: string; now: Date };

/** Published or done events starting (Paris day) within the school year. */
const yearEvents = (range: YearRange) => sql`
  select id, pole_id, starts_at, starts_at <= ${range.now.toISOString()}::timestamptz as started
  from event
  where deleted_at is null and status in ('published', 'done')
    and (starts_at at time zone 'Europe/Paris')::date between ${range.startsOn}::date and ${range.endsOn}::date`;

export function yearTotals(db: DbOrTx, range: YearRange) {
  return one(
    db,
    z.object({
      events: Count,
      registrations: Count,
      check_ins: Count,
      unique_participants: Count,
      started_confirmed: Count,
      started_check_ins: Count,
    }),
    sql`with ev as (${yearEvents(range)})
        select
          (select count(*) from ev) as events,
          (select count(*) from registration r join ev on ev.id = r.event_id
            where r.status <> 'cancelled') as registrations,
          (select count(*) from attendance a join ev on ev.id = a.event_id
            where a.kind = 'participant') as check_ins,
          (select count(distinct a.user_id) from attendance a join ev on ev.id = a.event_id
            where a.kind = 'participant') as unique_participants,
          (select count(*) from registration r join ev on ev.id = r.event_id
            where ev.started and r.status = 'confirmed') as started_confirmed,
          (select count(*) from attendance a join ev on ev.id = a.event_id
            where ev.started and a.kind = 'participant') as started_check_ins`,
  );
}

export function yearByMonth(db: DbOrTx, range: YearRange) {
  return rows(
    db,
    z.object({ month: z.string(), events: Count, check_ins: Count }),
    sql`with ev as (${yearEvents(range)})
        select to_char(ev.starts_at at time zone 'Europe/Paris', 'YYYY-MM') as month,
          count(distinct ev.id) as events,
          count(a.id) filter (where a.kind = 'participant') as check_ins
        from ev left join attendance a on a.event_id = ev.id
        group by 1 order by 1`,
  );
}

export function yearByPole(db: DbOrTx, range: YearRange) {
  return rows(
    db,
    z.object({
      pole_id: z.uuid(),
      pole_name: z.string(),
      events: Count,
      registrations: Count,
      check_ins: Count,
      started_confirmed: Count,
      started_check_ins: Count,
    }),
    sql`with ev as (${yearEvents(range)}),
        regs as (
          select r.event_id, count(*) filter (where r.status <> 'cancelled') as active,
            count(*) filter (where r.status = 'confirmed') as confirmed
          from registration r join ev on ev.id = r.event_id group by r.event_id),
        ins as (
          select a.event_id, count(*) as n from attendance a join ev on ev.id = a.event_id
          where a.kind = 'participant' group by a.event_id)
        select p.id as pole_id, p.name as pole_name,
          count(ev.id) as events,
          coalesce(sum(regs.active), 0) as registrations,
          coalesce(sum(ins.n), 0) as check_ins,
          coalesce(sum(regs.confirmed) filter (where ev.started), 0) as started_confirmed,
          coalesce(sum(ins.n) filter (where ev.started), 0) as started_check_ins
        from ev join pole p on p.id = ev.pole_id
        left join regs on regs.event_id = ev.id
        left join ins on ins.event_id = ev.id
        group by p.id, p.name order by p.name`,
  );
}

/** Active memberships of the year, one row per membership. */
export function yearMemberships(db: DbOrTx, schoolYearId: string) {
  return rows(
    db,
    z.object({
      user_id: z.uuid(),
      user_name: z.string(),
      role: z.string(),
      pole_id: z.uuid().nullable(),
      pole_name: z.string().nullable(),
    }),
    sql`select m.user_id, u.name as user_name, m.role, p.id as pole_id, p.name as pole_name
        from membership m join "user" u on u.id = m.user_id
        left join pole p on p.id = m.pole_id
        where m.school_year_id = ${schoolYearId} and m.is_active and m.deleted_at is null
        order by u.name`,
  );
}

/** Staff check-ins per person at the year's events. */
export function yearStaffShifts(db: DbOrTx, range: YearRange) {
  return rows(
    db,
    z.object({ user_id: z.uuid(), n: Count }),
    sql`with ev as (${yearEvents(range)})
        select a.user_id, count(*) as n from attendance a join ev on ev.id = a.event_id
        where a.kind = 'staff' group by a.user_id`,
  );
}

const yearMeetings = (range: YearRange) => sql`
  select id, pole_id from meeting
  where starts_at <= ${range.now.toISOString()}::timestamptz
    and (starts_at at time zone 'Europe/Paris')::date between ${range.startsOn}::date and ${range.endsOn}::date`;

/** Past meetings of the year per pole (null: general meetings). */
export function yearMeetingsHeld(db: DbOrTx, range: YearRange) {
  return rows(
    db,
    z.object({ pole_id: z.uuid().nullable(), n: Count }),
    sql`with mt as (${yearMeetings(range)}) select pole_id, count(*) as n from mt group by pole_id`,
  );
}

export function yearMeetingsAttended(db: DbOrTx, range: YearRange) {
  return rows(
    db,
    z.object({ user_id: z.uuid(), n: Count }),
    sql`with mt as (${yearMeetings(range)})
        select ma.user_id, count(*) as n from meeting_attendance ma join mt on mt.id = ma.meeting_id
        group by ma.user_id`,
  );
}
